### ISSUE TITLE
Error using % on  "like" where filters

### ISSUE THREAD

**Issue by LynxEyes** [hasankhan/sql-cli#10]
Everytime I use a '%' on a where filter mssql just blows up

```
$ mssql -s <address> -u <user> -p <password> -d <database>
Connecting to <address>...done

sql-cli version 0.4.4
Enter ".help" for usage hints.
mssql> select rec.nombre, cat.titulo from categoria cat inner join recurso_categoria rc on (cat.idcategoria = rc.idcategoria) inner join recurso rec on (rec.idrecurso = rc.idrecurso) where rec.nombre not like 'Ajudante%' order by rec.nombre;

/usr/local/lib/node_modules/sql-cli/node_modules/underscore.string/lib/underscore.string.js:176
          throw new Error('[_.sprintf] huh?');
                ^
Error: [_.sprintf] huh?
    at Function.str_format.parse (/usr/local/lib/node_modules/sql-cli/node_modules/underscore.string/lib/underscore.string.js:176:17)
    at str_format (/usr/local/lib/node_modules/sql-cli/node_modules/underscore.string/lib/underscore.string.js:79:53)
    at DbService.query (/usr/local/lib/node_modules/sql-cli/lib/dbservice.js:23:29)
    at Object.runQuery (/usr/local/lib/node_modules/sql-cli/lib/commands.js:14:16)
    at QueryCommand.run (/usr/local/lib/node_modules/sql-cli/lib/commands.js:63:22)
    at Invoker.run (/usr/local/lib/node_modules/sql-cli/lib/commands.js:341:29)
    at SqlCli._runCommand (/usr/local/lib/node_modules/sql-cli/lib/cli.js:100:22)
    at Prompt.emit (events.js:95:17)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
```

Any ideia why? Thanks!

**Comment by hasankhan** [comment]
We should not do sprintf in DBService https://github.com/hasankhan/sql-cli/blob/master/lib/dbservice.js#L23 
We should move query formatting to queries.js by making the methods accept arguments.
This would fix the issue. Do you want to fix this and send a pull request?
