### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by soobrosa** [hasankhan/sql-cli#13]
Every SQL query drops
```
/usr/local/lib/node_modules/sql-cli/lib/cli.js:100
        this.invoker.run(line)
                     ^
TypeError: Cannot call method 'run' of undefined
    at SqlCli._runCommand (/usr/local/lib/node_modules/sql-cli/lib/cli.js:100:22)
    at Prompt.emit (events.js:95:17)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)
    at ReadStream.onkeypress (readline.js:100:10)
    at ReadStream.emit (events.js:98:17)
    at emitKey (readline.js:1096:12)
    at ReadStream.onData (readline.js:841:14)
```

**Comment by soobrosa** [comment]
Randomly figured that `-e` solved it.
