### ISSUE TITLE
Doesn't handle large files

### ISSUE THREAD

**Issue by bjm88** [hasankhan/sql-cli#21]
If I try to load entire file that is 2.2 Gigs (from full db backup) it fails...

mssql> .run C:\Users\Administrator\Documents\schools_data\ridgefieldct\files\r1.sql
C:\Users\Ben\AppData\Roaming\npm\node_modules\sql-cli\lib\commands.js:43
            buffer += '\r\n';
                   ^

RangeError: Invalid string length
    at Object.appendLine (C:\Users\Ben\AppData\Roaming\npm\node_modules\sql-cli\lib\commands.js:43:20)
    at LineByLineReader.<anonymous> (C:\Users\Ben\AppData\Roaming\npm\node_modules\sql-cli\lib\commands.js:199:32)
    at emitOne (events.js:96:13)
    at LineByLineReader.emit (events.js:188:7)
    at LineByLineReader._nextLine (C:\Users\Ben\AppData\Roaming\npm\node_modules\sql-cli\node_modules\line-by-line\line-
by-line.js:114:8)
    at Immediate.<anonymous> (C:\Users\Ben\AppData\Roaming\npm\node_modules\sql-cli\node_modules\line-by-line\line-by-li
ne.js:119:9)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

**Comment by erickangMSFT** [comment]
I experienced the same with AdeventureWorks sample database script which is about 550MB with .run command.

**Comment by hasankhan** [comment]
I'll take a look.

**Comment by hasankhan** [comment]
Problem solved in v0.4.8 (currently in dev branch). Will be released tomorrow.
