### ISSUE TITLE
Cann't install  Failed at the sql-cli@0.4.14 prepublish script 'crlf --set=LF bin/mssql'.

### ISSUE THREAD

**Issue by longlogicode** [hasankhan/sql-cli#35]
Hi ,

Thanks for great tool, however I can not install due to issue below: 

npm install -g
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> sql-cli@0.4.14 prepublish /Users/mon/sql-cli
> crlf --set=LF bin/mssql

sh: crlf: command not found
npm ERR! addLocal Could not install /Users/mon/sql-cli
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! sql-cli@0.4.14 prepublish: `crlf --set=LF bin/mssql`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sql-cli@0.4.14 prepublish script 'crlf --set=LF bin/mssql'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sql-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     crlf --set=LF bin/mssql
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sql-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sql-cli
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mon/.npm/_logs/2017-03-23T09_27_25_958Z-debug.log

Mon-MacBook-Pro:sql-cli mon$ npm -v
4.4.4
Mon-MacBook-Pro:sql-cli mon$ node -v
v6.9.1

**Comment by hasankhan** [comment]
Please install latest version of node and try again.

**Comment by spiilmusic** [comment]
Same here with latest version of node and npm.
osx version:
ProductVersion:	10.12.4
BuildVersion:	16E195

```$ npm install -g
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> sql-cli@0.4.14 prepublish /Users/spiil/sql-cli
> crlf --set=LF bin/mssql

sh: crlf: command not found

npm ERR! addLocal Could not install /Users/spiil/sql-cli
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/bin/npm" "install" "-g"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! sql-cli@0.4.14 prepublish: `crlf --set=LF bin/mssql`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sql-cli@0.4.14 prepublish script 'crlf --set=LF bin/mssql'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sql-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     crlf --set=LF bin/mssql
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sql-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sql-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/spiil/.npm/_logs/2017-04-05T06_01_46_494Z-debug.log

$ node -v
v7.8.0
$ npm -v
4.2.0
```

And here is debug.log

```
$ cat /Users/spiil/.npm/_logs/2017-04-05T06_01_46_494Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.8.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g' ]
2 info using npm@4.2.0
3 info using node@v7.8.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData .
8 silly fetchDirectoryPackageData .
9 silly install normalizeTree
10 silly loadCurrentTree Finishing
11 silly loadIdealTree Starting
12 silly install loadIdealTree
13 silly cloneCurrentTree Starting
14 silly install cloneCurrentTreeToIdealTree
15 silly cloneCurrentTree Finishing
16 silly loadShrinkwrap Starting
17 silly install loadShrinkwrap
18 silly loadShrinkwrap Finishing
19 silly loadAllDepsIntoIdealTree Starting
20 silly install loadAllDepsIntoIdealTree
21 silly resolveWithNewModule sql-cli@0.4.14 checking installable status
22 silly cache add args [ '.', null ]
23 verbose cache add spec .
24 silly cache add parsed spec Result {
24 silly cache add   raw: '.',
24 silly cache add   scope: null,
24 silly cache add   escapedName: null,
24 silly cache add   name: null,
24 silly cache add   rawSpec: '.',
24 silly cache add   spec: '/Users/spiil/sql-cli',
24 silly cache add   type: 'directory' }
25 verbose addLocalDirectory /Users/spiil/.npm/sql-cli/0.4.14/package.tgz not in flight; packing
26 verbose correctMkdir /Users/spiil/.npm correctMkdir not in flight; initializing
27 verbose makeDirectory /Users/spiil/.npm creation not in flight; initializing
28 silly makeDirectory /Users/spiil/.npm uid: 501 gid: 20
29 warn prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
30 warn prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
31 warn prepublish-on-install See the deprecation note in `npm help scripts` for more information.
32 info lifecycle sql-cli@0.4.14~prepublish: sql-cli@0.4.14
33 verbose lifecycle sql-cli@0.4.14~prepublish: unsafe-perm in lifecycle true
34 verbose lifecycle sql-cli@0.4.14~prepublish: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/spiil/sql-cli/node_modules/.bin:/usr/local/mysql/bin:/Users/spiil/projects/chef_repo:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
35 verbose lifecycle sql-cli@0.4.14~prepublish: CWD: /Users/spiil/sql-cli
36 silly lifecycle sql-cli@0.4.14~prepublish: Args: [ '-c', 'crlf --set=LF bin/mssql' ]
37 info lifecycle sql-cli@0.4.14~prepublish: Failed to exec prepublish script
38 error addLocal Could not install /Users/spiil/sql-cli
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: sql-cli@0.4.14 prepublish: `crlf --set=LF bin/mssql`
43 verbose stack spawn ENOENT
43 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
43 verbose stack     at emitTwo (events.js:106:13)
43 verbose stack     at ChildProcess.emit (events.js:194:7)
43 verbose stack     at maybeClose (internal/child_process.js:899:16)
43 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
44 verbose pkgid sql-cli@0.4.14
45 verbose cwd /Users/spiil/sql-cli
46 error Darwin 16.5.0
47 error argv "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/bin/npm" "install" "-g"
48 error node v7.8.0
49 error npm  v4.2.0
50 error file sh
51 error code ELIFECYCLE
52 error errno ENOENT
53 error syscall spawn
54 error sql-cli@0.4.14 prepublish: `crlf --set=LF bin/mssql`
54 error spawn ENOENT
55 error Failed at the sql-cli@0.4.14 prepublish script 'crlf --set=LF bin/mssql'.
55 error Make sure you have the latest version of node.js and npm installed.
55 error If you do, this is most likely a problem with the sql-cli package,
55 error not with npm itself.
55 error Tell the author that this fails on your system:
55 error     crlf --set=LF bin/mssql
55 error You can get information on how to open an issue for this project with:
55 error     npm bugs sql-cli
55 error Or if that isn't available, you can get their info via:
55 error     npm owner ls sql-cli
55 error There is likely additional logging output above.
56 verbose exit [ 1, true ]
```

**Comment by hasankhan** [comment]
I'll fix this tonight

**Comment by hasankhan** [comment]
fixed, look out for next releasee

**Comment by spiilmusic** [comment]
Now the installation is working - I confirm. 
Thank you @hasankhan
