### ISSUE TITLE
String length crapping out 

### ISSUE THREAD

**Issue by fxfactorial** [hasankhan/sql-cli#41]
I think it might be because of some unicode stuff? 
```
/usr/local/lib/node_modules/sql-cli/lib/resultwriter.js:120
            this.log(prefix + JSON.stringify(result || [], null, 4));
                                   ^

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at JsonWriter.writeRows (/usr/local/lib/node_modules/sql-cli/lib/resultwriter.js:120:36)
    at finishRecordset (/usr/local/lib/node_modules/sql-cli/lib/commands/utils.js:31:28)
    at Request.request.on.returnValue (/usr/local/lib/node_modules/sql-cli/lib/commands/utils.js:71:25)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at /usr/local/lib/node_modules/sql-cli/node_modules/mssql/lib/main.js:1387:26
    at Request.userCallback (/usr/local/lib/node_modules/sql-cli/node_modules/mssql/lib/tedious.js:851:28)
    at Request.callback (/usr/local/lib/node_modules/sql-cli/node_modules/tedious/lib/request.js:33:27)
    at Connection.message (/usr/local/lib/node_modules/sql-cli/node_modules/tedious/lib/connection.js:1179:27)
```

**Comment by hasankhan** [comment]
Can you tell us what is the value that is causing this? Try emitting output in other format with -f switch so you can see what value is it.

**Comment by fxfactorial** [comment]
@hasankhan

Interesting, it only happens when redirected with a file. Its about 2 million rows, maybe like 7 columns. 

```
mssql --requestTimeout 999999999 --server 192.168.1.133 --user resquared --pass Resquared@sql --database Resquared -q 'select *  from GG.orders where fare is not null' --format json > ffff
/usr/local/lib/node_modules/sql-cli/lib/resultwriter.js:120
            this.log(prefix + JSON.stringify(result || [], null, 4));
                                   ^

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at JsonWriter.writeRows (/usr/local/lib/node_modules/sql-cli/lib/resultwriter.js:120:36)
    at finishRecordset (/usr/local/lib/node_modules/sql-cli/lib/commands/utils.js:31:28)
    at Request.request.on.returnValue (/usr/local/lib/node_modules/sql-cli/lib/commands/utils.js:71:25)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at /usr/local/lib/node_modules/sql-cli/node_modules/mssql/lib/main.js:1387:26
    at Request.userCallback (/usr/local/lib/node_modules/sql-cli/node_modules/mssql/lib/tedious.js:851:28)
    at Request.callback (/usr/local/lib/node_modules/sql-cli/node_modules/tedious/lib/request.js:33:27)
    at Connection.message (/usr/local/lib/node_modules/sql-cli/node_modules/tedious/lib/connection.js:1179:27)
```

**Comment by hasankhan** [comment]
We should update the code to use JSONStream to stream the JSON to file instead of writing it as one big chunk.

**Comment by fxfactorial** [comment]
Yes, it should be a stream because for real world usage many data sets will cause this crap out.

**Comment by hasankhan** [comment]
Can you try the latest version to see if it resolves your issue?

**Comment by fxfactorial** [comment]
Sorry, this came up during a hackathon and I don't have the context anymore. I hope your fix does work though.
