### ISSUE TITLE
Getting error while connecting to mssql

### ISSUE THREAD

**Issue by bhaskardabhi** [hasankhan/sql-cli#53]
bhaskardabhi@Bhaskars-MacBook-Pro-2 ~/p/fleetfoot> sudo mssql -u mssql -p d@bhi1234
/usr/local/lib/node_modules/sql-cli/node_modules/password-prompt/index.js:106
  )
  ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/sql-cli/lib/options.js:9:22

    at Object.<anonymous> (/usr/local/lib/node_modules/sql-cli/lib/options.js:111:3)

**Comment by toddroper** [comment]
Duplicate of #52 
This issue should be closed and @bhaskardabhi should subscribe to #52.
